# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pugmark < Formula
  desc "The durable agent runtime built on object storage"
  homepage "https://github.com/firetiger-oss/pugmark"
  version "0.16.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.7/pugmark_0.16.7_darwin_amd64.tar.gz"
      sha256 "3678bfb19093e8418ff4f5a041c32491d3815c85aa8202eaaa7d8150c48fa9f2"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.7/pugmark_0.16.7_darwin_arm64.tar.gz"
      sha256 "740984b8d90385522c9683fd32b4b89aaa7be792271a27eb98bbb8892d6c2c72"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.7/pugmark_0.16.7_linux_amd64.tar.gz"
      sha256 "346fe3a2de14cc3cecba4f62b42896143a90582809473cce3c9d63d0189b5f31"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.7/pugmark_0.16.7_linux_arm64.tar.gz"
      sha256 "17999d5e5418cc611a622c84091934caf105489eec7f103c030193cfacb58f45"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pugmark version")
  end
end
