# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pugmark < Formula
  desc "The durable agent runtime built on object storage"
  homepage "https://github.com/firetiger-oss/pugmark"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.0/pugmark_0.16.0_darwin_amd64.tar.gz"
      sha256 "1ebb4ff4d6e6a1d63e0d8a1c700032c8c53ddf1d07f7a50cf939fc32f4897320"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.0/pugmark_0.16.0_darwin_arm64.tar.gz"
      sha256 "ab26c6d6ed3782da8a582ec33e826356f108fa9933276b6799af128f08c0e4af"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.0/pugmark_0.16.0_linux_amd64.tar.gz"
      sha256 "e0fed2e072103b3ad38c005c674a0edc5fbe50400b94e87104f2fc90a1e1927e"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.0/pugmark_0.16.0_linux_arm64.tar.gz"
      sha256 "031bb436410e35a389eed893ce96a18196cf8806ee59a71982bbd44f9f375011"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pugmark version")
  end
end
