# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pugmark < Formula
  desc "The durable agent runtime built on object storage"
  homepage "https://github.com/firetiger-oss/pugmark"
  version "0.16.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.2/pugmark_0.16.2_darwin_amd64.tar.gz"
      sha256 "99136f881237abbebc131dc1511e59122b465349a5ab657d11dfba21dadb5752"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.2/pugmark_0.16.2_darwin_arm64.tar.gz"
      sha256 "2ac96fbdecffdda764ee8a143a64008267ad0c5d577756471441841de3c61380"

      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.2/pugmark_0.16.2_linux_amd64.tar.gz"
      sha256 "306b0f4f7342824d28224efa31179a8f4cf0a30f2086b6896f3b3f930a518c4a"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/pugmark/releases/download/v0.16.2/pugmark_0.16.2_linux_arm64.tar.gz"
      sha256 "020b3106b27fe0ffedd03b3a087b2ae314376a16350f3a07bf9bd08995d427a7"
      define_method(:install) do
        bin.install "pugmark"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pugmark version")
  end
end
