# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stripes < Formula
  desc "Streaming pretty-printer for structured data formats — JSON, YAML, XML, CSV, parquet, source code, and more."
  homepage "https://github.com/firetiger-oss/stripes"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/stripes/releases/download/v0.3.0/stripes_0.3.0_darwin_amd64.tar.gz"
      sha256 "d4446771e354c6a96885210ade22d7cd30d08d9fc85ec8bc802f5467fce77439"

      define_method(:install) do
        bin.install "stripes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/stripes/releases/download/v0.3.0/stripes_0.3.0_darwin_arm64.tar.gz"
      sha256 "c5209647078a84b82d18ff4548bf92414bcff049c26b0defb610076d88a5ee9d"

      define_method(:install) do
        bin.install "stripes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/stripes/releases/download/v0.3.0/stripes_0.3.0_linux_amd64.tar.gz"
      sha256 "53217031fe932108f7a92679c167fd0abd173dd1d5f06f5ac40d7878c451a837"
      define_method(:install) do
        bin.install "stripes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/stripes/releases/download/v0.3.0/stripes_0.3.0_linux_arm64.tar.gz"
      sha256 "adc987bd337d27b7d314b02c34575360c92ddefed8d7dd8c49b0f220f705271d"
      define_method(:install) do
        bin.install "stripes"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stripes --version")
  end
end
