# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T4 < Formula
  desc "CLI for object storage across S3, GCS, R2, HTTP, and the local filesystem"
  homepage "https://github.com/firetiger-oss/tigerblock"
  version "0.26.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.26.0/t4_0.26.0_darwin_amd64.tar.gz"
      sha256 "c0fc882a9f8c54d38e5ae7961726f0a2468077a6ef3eac05c18f2f2fef477720"

      define_method(:install) do
        bin.install "t4"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.26.0/t4_0.26.0_darwin_arm64.tar.gz"
      sha256 "a6825045dfd3b6739d6f4b005500ee8b37a5b1dd5efa31e5fb57d04e7317a98d"

      define_method(:install) do
        bin.install "t4"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.26.0/t4_0.26.0_linux_amd64.tar.gz"
      sha256 "3cc40ffbb133e444858deb954ac3205bb273232cd350c13566014ab39f4fe818"
      define_method(:install) do
        bin.install "t4"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.26.0/t4_0.26.0_linux_arm64.tar.gz"
      sha256 "df2ad44877780e6cceb88cfbcc9294f81d10088236bd833016c5018a5ec84433"
      define_method(:install) do
        bin.install "t4"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/t4 --version")
  end
end
