# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T4 < Formula
  desc "CLI for object storage across S3, GCS, R2, HTTP, and the local filesystem"
  homepage "https://github.com/firetiger-oss/tigerblock"
  version "0.27.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.27.1/t4_0.27.1_darwin_amd64.tar.gz"
      sha256 "0e9007d4f474ac9bbeafe4a339e1dede8950bc971275bc6a1d3b10a0a67751bf"

      define_method(:install) do
        bin.install "t4"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.27.1/t4_0.27.1_darwin_arm64.tar.gz"
      sha256 "8a2766bcda2db83b808605fc5ad8402c4bd1c9068f017650dce4ade27c933790"

      define_method(:install) do
        bin.install "t4"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.27.1/t4_0.27.1_linux_amd64.tar.gz"
      sha256 "ef4dec9730b5ec099dd1cc41e15220b8f585fbe163624b8f9368022e5f28d452"
      define_method(:install) do
        bin.install "t4"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firetiger-oss/tigerblock/releases/download/v0.27.1/t4_0.27.1_linux_arm64.tar.gz"
      sha256 "006e5aa3238e87b24f38e938d8ac7d4b383dbf61457ea4c1785a8671b3235055"
      define_method(:install) do
        bin.install "t4"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/t4 --version")
  end
end
